### ISSUE TITLE
Góp ý: Khi tạo bài viết

### ISSUE THREAD

**Issue by phongaz** [hoaquynhtim99/blog#3]
Khi tạo bài viết nếu module chưa có chuyên mục nào thì nên chuyển hướng đến trang thêm chuyên mục hoặc thông báo để tạo chuyên mục trước rồi mới viết bài

Hiện tại mình viết bài xong nhưng không có chuyên mục để gắn vào

Khi lưu bài viết nhưng vì chưa có chuyên mục nên không thể lưu được, hệ thống hỏi có load lại nội dung đã lưu trước đó không, --> mình chọn OK thì xuất hiện như sau: Nội dung nó tràn ra khỏi editor, khi sửa bài viết cũng bị như thế

![vietbai b l i](https://cloud.githubusercontent.com/assets/6806295/5397396/bd87f58a-818c-11e4-9897-ab52369e1792.PNG)

**Comment by hoaquynhtim99** [comment]
Phần tạo chuyên mục chỉ xảy ra một lần duy nhất khi cài đặt nên không nhất thiết phải code thêm.
Phần tự lưu hoàn toàn do Ckeditor không phải chức năng của module
