### ISSUE TITLE
Lỗi bỏ tên module này khỏi URL

### ISSUE THREAD

**Issue by phongaz** [hoaquynhtim99/blog#5]
Khi bỏ tên module này ra khỏi URL thì khi xem bài viết hệ thống chuyển về module page

**Comment by hoaquynhtim99** [comment]
Phần này đã kiểm tra đó là vấn đề của NukeViet module không thể can thiệp được, module này đã tối ưu URL gọn nhất có thể do đó khuyến nghị mọi người cũng không nên bỏ tên module khỏi url
